export const projects = [
  {
    id: 1,
    title: "KapwaFi",
    description: "Blockchain hackathon project — decentralized on-chain lending platform built on Stellar. APAC Demo Day winner, connecting community finance to DeFi infrastructure.",
    tech: ["TypeScript", "Stellar SDK", "Blockchain", "React"],
    tags: ["Blockchain"],
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=2089",
    video: "/kapwafi.mp4",
    link: "https://github.com/l9rins/kapwafi",
    github: "https://github.com/l9rins/kapwafi",
    stats: [
      { label: "Platform", value: "Stellar" },
      { label: "Event", value: "APAC Week" },
      { label: "Type", value: "DeFi" },
    ],
    color: "#ffffff",
  },
  {
    id: 2,
    title: "SutoyDB",
    description: "Redis-compatible in-memory key-value store built from scratch using Java Virtual Threads. High-performance concurrent data structure server.",
    tech: ["Java", "Virtual Threads", "Redis Protocol", "Networking"],
    tags: ["Infrastructure"],
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2074",
    video: "",
    link: "https://github.com/l9rins/SutoyDB",
    github: "https://github.com/l9rins/SutoyDB",
    stats: [
      { label: "Concurrency", value: "Virtual Threads" },
      { label: "Protocol", value: "Redis" },
      { label: "Language", value: "Java" },
    ],
    color: "#ffffff",
  },
  {
    id: 3,
    title: "AWS Cloud Sec Advisor",
    description: "AI-powered cloud security assistant — analyzes AWS configurations and generates compliance policies using Anthropic's Claude API.",
    tech: ["Python", "AWS", "Anthropic API", "Security"],
    tags: ["Security", "AI/ML"],
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2070",
    video: "",
    link: "https://github.com/l9rins/aws-cloud-security-policy-advisor",
    github: "https://github.com/l9rins/aws-cloud-security-policy-advisor",
    stats: [
      { label: "AI", value: "Claude API" },
      { label: "Cloud", value: "AWS" },
      { label: "Focus", value: "Compliance" },
    ],
    color: "#ffffff",
  },
  {
    id: 4,
    title: "SecurCoachAI",
    description: "Interactive cybersecurity learning platform — AI-powered coaching system for threat detection and security best practices training.",
    tech: ["Python", "Streamlit", "AI/ML", "Cybersecurity"],
    tags: ["Security", "AI/ML"],
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2070",
    video: "",
    link: "https://github.com/l9rins/SecurCoachAI",
    github: "https://github.com/l9rins/SecurCoachAI",
    stats: [
      { label: "Platform", value: "Streamlit" },
      { label: "Domain", value: "Security" },
      { label: "Type", value: "AI Coach" },
    ],
    color: "#ffffff",
  },
];
